spring:
  application:
    name: nikke-hub-eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: nikke-hub-eureka-server
    preferIpAddress: true

  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/