apiVersion: v1
kind: Service
metadata:
  name: nikke-hub-eureka-server-service
spec:
  selector:
    app: nikke-hub-eureka-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: ClusterIP
