apiVersion: v1
kind: ConfigMap
metadata:
  name: nikke-hub-eureka-serve-config
data:

  EUREKA_SERVER_PORT: "8761"
  EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: "http://nikke-hub-eureka-server-service:8761/eureka/"

  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"

  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"

  EUREKA_CLIENT_FETCH_REGISTRY: "false"

  EUREKA_CLIENT_ENABLED: "false"

  EUREKA_SELF_PRESERVATION: "false"

  WAIT_TIME_SYNC: "0"